### ISSUE TITLE
Project build failed

### ISSUE THREAD

**Issue by milanpanin** [bradtraversy/property-pulse#2]
After successfully completing the course, I wanted to host the project on my private VPS. The problem occurs when I try to build the project. 

Error messeage:

```shell
property-pulse@0.1.0 build
next build

   ▲ Next.js 14.1.2
   
Environments: .env

   Creating an optimized production build ...
 ⚠ For production Image Optimization with Next.js, the optional 'sharp' package is strongly recommended. Run 'npm i sharp', and Next.js will use it automatically for Image Optimization.
Read more: https://nextjs.org/docs/messages/sharp-missing-in-production
Compiler client unexpectedly exited with code: null and signal: SIGTERM
 ✓ Compiled successfully
 ✓ Linting and checking validity of types
 ✓ Collecting page data
   Generating static pages (2/12)  [==  ]
TypeError: fetch failed
    at node:internal/deps/undici/undici:12500:13
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async globalThis.fetch (C:\Users\user\Desktop\property-pulse.next\server\chunks\638.js:1:36495)
    at async m (C:\Users\user\Desktop\property-pulse.next\server\app\page.js:1:8034)
    at async h (C:\Users\user\Desktop\property-pulse.next\server\app\page.js:1:8232) {
  [cause]: AggregateError [ECONNREFUSED]:
      at internalConnectMultiple (node:net:1116:18)
      at afterConnectMultiple (node:net:1683:7)
      at TCPConnectWrap.callbackTrampoline (node:internal/async_hooks:130:17) {
    code: 'ECONNREFUSED',
    [errors]: [ [Error], [Error] ]
  }
}
TypeError: Cannot read properties of undefined (reading 'sort')
    at h (C:\Users\user\Desktop\property-pulse.next\server\app\page.js:1:8254)
   Generating static pages (11/12) [  ==]
 ✓ Generating static pages (12/12)
 ✓ Collecting build traces
 ✓ Finalizing page optimization
```

**Comment by vineyy17** [comment]
Adding export const dynamic = 'force-dynamic'; to app/pages.js fixed that for me.
